# Generated by Django 3.2.5 on 2021-08-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='cost',
            field=models.BigIntegerField(),
        ),
    ]
