# Generated by Django 3.2.6 on 2021-08-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
